### ISSUE TITLE
Cambios web

### ISSUE THREAD

**Issue by LauCamacho** [osoc-es/website#5]
Cambiar FAQ principal: Edición online, dos semanas duración...

Web 2020: 
- Añadir nombres participantes: https://docs.google.com/spreadsheets/d/1Z7-6y_8S6FzLhBzrxLgiBGBX6j8v0bn3BX25igywQZ0/edit#gid=319775959 (Están en este documento)
- Añadir información proyectos

Web 2021: añadir formularios 
- Español: https://docs.google.com/forms/d/1TABbx03VbFgPQx4jERS7xi6cfI7SfDNRHl8MOlxXCwU/edit?usp=sharing
- ingles: https://docs.google.com/forms/d/104tH44uBMQf5N0WTxTX_wuu3Kv1XNRihq7bt7vN_xoY/edit?usp=sharing

**Comment by daniel-dona** [comment]
He estado revisando todo lo que había del año pasado porque es un poco caos al haber hecho dos webs (la inicial y luego cuando se canceló lo presencial la online), creo que podríamos convertir ambas en una sola, en plan "archivo histórico".

Sería juntar el contenido de https://online2020.summerofcode.es/ y https://2020.summerofcode.es/, creo que eso solucionaría los puntos respecto a la web del 2020, porque en una está la información de los proyectos, en otra no, e igual con los participantes. 

También luego de unirlas borraría el subdominio online2020, para dejar solo 2020 (aunque fuese online). 

Sobre la web del 2021, creo que lo mejor es tomar de referencia la de la versión online 2020 y actualizar. 

Sobre el dominio principal (summerofcode.es) ¿por qué no simplificar y redireccionar a la web de la edición actual? Tenemos demasiadas copias de la web y eso siempre genera más problemas, así lo dejamos en una actual y una histórica.

**Comment by dachafra** [comment]
agree en todo. Adelante

**Comment by dachafra** [comment]
pero con prioridad de que la web de esta año debe estar up&running asap

**Comment by daniel-dona** [comment]
Voy a abrir varios issues y así registramos mejor todas las cosas que puede que haya que cambiar y es más fácil para @LauCamacho. 

Algunas cosas están pendientes de gestiones de sysadmin, así que puede que tarden un poco en verse reflejadas en la web.
