### ISSUE TITLE
Cambios en FAQ

### ISSUE THREAD

**Issue by daniel-dona** [osoc-es/website#6]
La última FAQ que se redactó, para la edición online del año pasado es esta: https://online2020.summerofcode.es/practical.html

Habría que revisar si hay algún cambio notable en ella que incorporar o si conviene añadir algo más. 

Lo más relevante a cambiar me parecen las fechas, que también salen en otras partes de la web, como en "Agenda":

https://online2020.summerofcode.es/agenda.html

**Comment by LauCamacho** [comment]
Si, en principio el cambio mas destacable seria cambiar las fechas que figuran ( este año es del 5 al 16 de julio) como dices, y el año del hashtag principalmente

**Comment by daniel-dona** [comment]
Tengo algunas dudas sobre las fechas, ¿cuándo sería el Demo Day? ¿el 17?

**Comment by LauCamacho** [comment]
Este año seria el 16 en principio

**Comment by daniel-dona** [comment]
Y en fecha de publicación ponemos el 10 por ejemplo? Este lunes.
![imagen](https://user-images.githubusercontent.com/23705091/117445722-50e44300-af3b-11eb-9264-2d1d075e2273.png)

**Comment by LauCamacho** [comment]
si, yo creo que para moverlo ya todo es buena fecha. Yo dejo todo preparado y asi ya el lunes se presenta

**Comment by daniel-dona** [comment]
Perfecto!
