### ISSUE TITLE
Retos

### ISSUE THREAD

**Issue by daniel-dona** [osoc-es/website#8]
El año pasado se elaboró esta sección, https://2021.summerofcode.es/challenges.html

¿Los retos son similares o hay que volver a redactarlos?

**Comment by dachafra** [comment]
Habrá que volver a redactarlos, de momento puede quedar vacía

**Comment by daniel-dona** [comment]
Vale, por ahora dejamos solo un par de apartados y vamos añadiendo contenido según se tenga. Cuando se añada algo relevante se puede publicar en redes para darle difusión.
